uploads = []
generated = []

[[outputs]]
id = "OAyjY3fXxBAcVDWh7I2H6"
uri = "file://exports/webhook.py.txt"
type = "text"
title = "webhook.py - النسخة النهائية (1l.u + play_url أولاً)"

[[outputs]]
id = "kI1MW0R_VjOa06ZJnbEOr"
uri = "file://exports/app.py.txt"
type = "text"
title = "2️⃣ app.py - أحدث نسخة (191 سطر - md5 ff160b26)"
